In [69]:
import scipy.optimize
import scipy.integrate
import numpy

In [50]:
import math
def f(r, d, a, r0):
    #d, a, r0 = p0
    e=numpy.exp(-a*(r-r0))
    return d*(1-e)**2

def g(r):
    d=2.5; a=1.5; r0=0.5
    e=numpy.exp(-a*(r-r0))
    return numpy.array([2*d*(1-e)*(a*e)])

def h(r):
    d=2.5; a=1.5; r0=0.5
    e=numpy.exp(-a*(r-r0))
    return 2*a*d*(-a*e*(1-e) + e*(a*e))


In [46]:
scipy.optimize.brent(f)

0.5000000017938965

In [15]:
scipy.optimize.fmin_cg(f, [1])

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 2
         Function evaluations: 39
         Gradient evaluations: 12


array([0.49999999])

In [17]:
scipy.optimize.fmin_cg(f, [1], fprime=g)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 2
         Function evaluations: 15
         Gradient evaluations: 12


array([0.5])

In [19]:
scipy.optimize.fmin_ncg(f, [1], fprime=g)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 5
         Function evaluations: 8
         Gradient evaluations: 22
         Hessian evaluations: 0


array([0.5])

In [21]:
scipy.optimize.fmin_ncg(f, [1], fprime=g, fhess=h)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 5
         Function evaluations: 8
         Gradient evaluations: 12
         Hessian evaluations: 5


array([0.5])

In [32]:
scipy.optimize.fmin_bfgs(f, [1], fprime=g)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 6
         Function evaluations: 9
         Gradient evaluations: 9


array([0.5])

## Curve fitting

In [33]:
x = numpy.arange(0, 5, .1)

In [36]:
y = f(x) + 0.001*numpy.random.normal(len(x))

In [52]:
scipy.optimize.curve_fit(f, x, y, p0=(2.5, 1.5, 0.5))

(array([2.97730457, 1.67881812, 0.45423497]),
 array([[ 0.00147229, -0.00101618,  0.00016892],
        [-0.00101618,  0.00218375, -0.00042993],
        [ 0.00016892, -0.00042993,  0.00012127]]))

## Least square

In [53]:
    import numpy
    from scipy.optimize import leastsq
    x = numpy.arange(0, 10, .01)
    k0 = 3.0
    l0 = 1.0
    y = k0 * x + l0 + numpy.random.randn(len(x))

In [56]:
    def resid(p, y, x):
       k,l = p
       return y - k*x - l

In [57]:
p0 = numpy.array([k0, l0])

In [58]:
plsq = scipy.optimize.leastsq(resid, p0, args=(y, x))

In [59]:
plsq

(array([2.98697324, 1.05689535]), 2)

## Integration

In [70]:
#from scipy.integrate import quad
sqrtpi = math.sqrt(math.pi)
def e2(x):
    return math.exp(-x*x)

In [72]:
scipy.integrate.quad(e2, -10, 10)

(1.772453850905516, 3.695852112137264e-13)

In [73]:
math.sqrt(math.pi)

1.7724538509055159